### ISSUE TITLE
 Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by rush1818** [EulerianTechnologies/gtm-ss-eulerian-analytics#1]
When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by matjmat** [comment]
Hi @rush1818 thanks for your comment but we are POSTing the data as a JSON payload once the full object is created and thus don't need any encoding. So we do not see where we need to do the modifications you are suggesting. Thanks.

**Comment by rush1818** [comment]
I see you're generating the URL via `targetHost` which is a user input. You should encode it to avoid any issues due to bad input.

**Comment by matjmat** [comment]
hi @rush1818 
 ok i see, however it's a domain url so I suggest we modify the `targetHost` configuration to implement a regexp check :

`
 "valueValidators": [
      {
        "type": "REGEX",
        "args": [
          "^[a-z0-9\\-]+$"
        ]
      }
    ],
`

Rather then having only a NON_EMPTY check.

That way we are sure we authorize values of the type : 

1. io1
2. io1-test
3. 98test
4. test

etc...

Would that work for you ?

If ok i'll modify the template & hash.

Best,

**Comment by rush1818** [comment]
Value validator will certainly help catch any issues earlier and would be a good addition. However, I still recommend encoding it when the final URL is constructed in the code.

**Comment by matjmat** [comment]
@rush1818 hi, we did the modification is it all good on your end ? thanks.

**Comment by rush1818** [comment]
@matjmat I think there are invalid newlines in the `thumbnail` value. Could you fix and update the metadata again?

**Comment by matjmat** [comment]
hi @rush1818 I don't see where, after downloading the template.tpl file, if you edit it in vim everything is on one line for the thumbnail value.

**Comment by rush1818** [comment]
I see the value split between 3 lines in the raw content view within Github as well. Try parsing the entire INFO object as JSON and you should see an error because of that.

**Comment by matjmat** [comment]
that's an issue with git, in the file it's on one line, you can check by opening it in another editor.

**Comment by rush1818** [comment]
Its same issue when opened with VSCode. Can you check again?

**Comment by matjmat** [comment]
could you check last commit : https://github.com/EulerianTechnologies/gtm-ss-eulerian-analytics/blob/main/template.tpl

**Comment by rush1818** [comment]
Great, parsing worked now. Will queue it up for approval.

**Comment by matjmat** [comment]
@rush1818  thanks for your time & support during this process !
